Integrate file sync download to automatically import downloaded data into Redis
badgerloop-software/file_sync pull request #5
Opened 2024-02-18 17:19 UTC by jackwherry

To test these changes,
* chase-car-dashboard must be on the `file_sync_integration` branch
* file_sync (now a  submodule of chase-car-dashboard) must be on the `database_import` branch

See https://github.com/badgerloop-software/chase-car-dashboard/pull/76

2024-02-20 04:09 UTC, MCLiii commented
Looks good, once the chase car end is implemented and tested with call back I'll approve this

2024-04-18 17:38 UTC, MCLiii commented on file_sync_down/main.py
> +                callback(file) # TODO check whether this gets the DATA or just a file handle
```suggestion
                with open(fs_config.sync_folder_location + "/" + file, "rb") as f:
                    callback(f.read())
```

2024-04-18 17:40 UTC, MCLiii requested changes
URL also needs to be changed to fs.bsr-dev.org

2024-04-18 18:03 UTC, jackwherry commented
When this is ready to merge, we need to do it at the same time as https://github.com/badgerloop-software/chase-car-dashboard/pull/76

2024-04-18 18:53 UTC, MCLiii reviewed
Same url needs to be changed for file_sync_up

2024-04-18 19:47 UTC, jackwherry commented
Done. Do you want to do full scale testing on this as soon as I’m done with the new OS stack on the Pi? (i.e., using the actual Pi and server, with the car just sitting there)

2024-04-18 19:51 UTC, MCLiii commented
> Done. Do you want to do full scale testing on this as soon as I’m done with the new OS stack on the Pi? (i.e., using the actual Pi and server, with the car just sitting there)

I've done it with ethernet sim, seems to work. I am getting a url too long when there's too much files queued up, probably gonna increase the file size threashold for upload to 100kb and change zip downloads api to use post

2024-05-03 22:52 UTC, merged